#!/usr/bin/php
<?php

// repo root path
$sRootPath = exec('git rev-parse --show-toplevel', $res, $ret);
if ($ret) {
	exit(0);
}

// get list of files
exec('git diff --cached --name-only --diff-filter=ACMR', $aFiles);
if (!is_array($aFiles)) {
	exit(0);
}

$aForbiddenWords = ['FIXME', 'TODO', '<<<<<<', '======', '>>>>>>'];

// process all PHP files
$aErrors = [];
foreach ($aFiles as $sFile) {
	if (substr($sFile, -4) == '.php') {
		// check PHP file syntax
		exec('cat '. $sRootPath.'/'.$sFile .' | php -l', $aErrors);
	}
	
	$sContent = file_get_contents($sRootPath.'/'.$sFile);
	foreach ($aForbiddenWords as $sWord) {
		if (strpos($sContent, $sWord) !== FALSE) {
			$aErrors[] = '('.$sFile.') Mot interdit : '. $sWord .PHP_EOL;
		}
	}
}

// display errors
$iReturn = 0;
if (count($aErrors) > 1 || ($aErrors[0] !== 'No syntax errors detected in Standard input code')) {
	echo '=== ERRORS ==='.PHP_EOL;
	foreach ($aErrors as $sErr) {
		echo $sErr . PHP_EOL;
	}
	$iReturn = 1;
	echo '>> Commit annulé' . PHP_EOL;
}
exit($iReturn);
